version: '3'

services:
  postgres:
    container_name: meetapp_db
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: meetapp_backend
    build: .
    ports:
      - '3333:3333'
    command: yarn dev
    environment:
      - DB_HOST=meetapp_db
    volumes:
      - '.:/usr/app'

volumes:
  postgres_data:
